### ISSUE TITLE
Plugin management doesnt work

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/NTRDB#32]
![image](https://cloud.githubusercontent.com/assets/15308404/23339593/22c62de6-fc37-11e6-8725-5bbfb621a04e.png)

**Comment by OctoNezd** [comment]
Fixed with https://github.com/OctoNezd/NTRDB/commit/dbd246b0b6f4f1a2a384cd95d0c3985344589ced

**Comment by JourneyOver** [comment]
This issue is back again but it's a different line and error message..

http://i.imgur.com/OmFFg03.png

**Comment by pehcc** [comment]
Same

**Comment by OctoNezd** [comment]
Fixed, just forgot to update server-side
